## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    tcpclient = bld.create_ns3_module('tcp-client', ['core','network','internet'])
    tcpclient.source = [
        'model/tcpclient.cc',
        ]
    headers = bld(features='ns3header')
    headers.module = 'tcp-client'
    headers.source = [
        'model/tcpclient.h',
        ]
