## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('tcpmain',
                                 ['point-to-point', 'applications', 'internet','traffic-control'])
    obj.source = 'tcpmain.cc'
